vich_uploader:
    db_driver: orm

    mappings:
        images_livres:
            uri_prefix: '%images_livres%'
            upload_destination: '%kernel.project_dir%/public%images_livres%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true